# Set which worlds the TimeBar will show.
worlds-to-show-in:
  - "world"

# Set the color of the TimeBar.
# The valid options are: blue, green, pink, purple, red, white, and yellow.
bar-color: "blue"

# No touch please :)
config-version: 1