# Set which world will TimeBar show the time for.
world-to-track-time: "world"

# Set which worlds the TimeBar will show in.
worlds-to-show-in:
  - "world"

# Set the color of the TimeBar.
# The valid options are: blue, green, pink, purple, red, white, and yellow.
titlebar-color: "blue"

# Set the text of the TimeBar.
# {TIME} - The time to display. Dawn, afternoon, etc.
# {DAYCOUNT} - How many total days in game have passed.
timebar-title: "{TIME} (Day {DAYCOUNT})"

# Want to change the wording of the times?
times:
  dawn: "Dawn"
  morning: "Morning"
  noon: "Noon"
  afternoon: "Afternoon"
  sunset: "Sunset"
  night: "Night"
  midnight: "Midnight"


# No touch please :)
config-version: 3