name: TimeBar
version: ${project.version}
main: lol.hyper.timebar.TimeBar
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/timebar.90179/
description: See the world's time as a bossbar.
commands:
  timebar:
    aliases: [tb]
    usage: /timebar
    description: Main command.
libraries:
  - lol.hyper:github-release-api:1.0.1
  - net.kyori:adventure-api:4.10.1
  - net.kyori:adventure-platform-bukkit:4.1.0